### ISSUE TITLE
Issue with partial fixity in frames

### ISSUE THREAD

**Issue by iminano** [BHoM/SAP2000_Toolkit#248] opened 2021-06-09 09:17 UTC
Hi! I have a problem when I try to model partial fixities at the end nodes of the frames. The set up is the following:

![Captura](https://user-images.githubusercontent.com/83087647/121327477-c5801800-c913-11eb-9486-2279a275a84e.PNG)

This only happens when I try to attach the partial stiffness to the end-points of the frames, which returns a null when I push the objects, whereas if I try to model springs in nodes this does not happen.

Can someone help me out with this?

Thanks in advance.

IMG

**Comment by IsakNaslundBh** [comment] 2021-12-23 08:26
For reference, the tweaks made to ETABS_Adapter to try to remedy this can be found here: https://github.com/BHoM/ETABS_Toolkit/pull/394

**Comment by IsakNaslundBh** [comment] 2021-12-23 08:32
@iminano what you could try until this has been sorted, is to make sure the DOFType for the DOF you want to assign a stiffness to is set to `Free`. I think that should work with the current code. This is not the intended behaviour, the intended behaviour is for the DOF type to be `Spring` for this case, but should hopefully work as a temporary fix for you issue until this has been fixed in the adapter.
![image](https://user-images.githubusercontent.com/22005920/147212014-e25b93c8-eeca-4037-96ca-929cdcb82c22.png)

**Closed** 2022-01-11 16:30 UTC
Labels: type:bug
